# Generated by Django 4.1 on 2024-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_doctors_book_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='contact_number',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='department',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
